site_name: PHY 315 Introduction to Computational Methods in Physics 

nav:
    - Home: index.md
    - Introduction: ch1_intro.md
    - Symbolic and Plotting Tools: ch2_symbolic.md
    - Numerical Methods: ch3_numeric.md
    - Curve Fitting and Optimization: ch4_fitting.md
    - Fourier Transform: ch5_fouriertransform.md
    - Monte Carlo Methods: ch6_montecarlo.md
    - Machine Learning Example: ch7_mltools.md
    - Further References: references.md 

theme:
    name: material
    features:
      - content.code.annotate
      - content.tabs.link
    palette:
      primary: teal
      scheme: default
    
    
markdown_extensions:
    - meta
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.details
    - attr_list
    - pymdownx.keys
        
plugins:
    - search
    - enumerate-headings:
        exclude:
          - index.md
          - references.md
    - mkdocs-jupyter:
        execute: true
        ignore_h1_titles: true
        
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://cdn.jsdelivr.net/npm/p5@1.4.1/lib/p5.js
